language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
before_script:
- "./.travis/prepare.sh"
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    tags: true
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.11.12" && "${TRAVIS_JDK_VERSION}" == "oraclejdk8"'
env:
  global:
  - secure: HC0qAup5Xmd00W6opHApcjRr29EDENrM5CmUhBfRkyayt1zoKLGfIs2nxiNcKKNBh1jCY4zE5JSahOefEvgTsbmKsuPAkBQa0TsPmldSHvcMEhyX9yxneVuZwQjfLdYP08ocJqMbGaDRHOzpbMyKT+/KDSinE85yzKp6mtZ0dAG26hymKI5vzJBi6ELF1z5f1DwlNLDQShifPj7NqQRL7lEuwf3MuPgD/4Mzse49fFxi1zr9wlHfcoOy0NyLcaPMpE6lfXszpnS9B0Tx/PvTL0UQhbbT8WdE+88VxZoXHewWDrpEFNHTTMGG1qwKaplcXxQnl3aHJoVNOm0ElReFvTvyHGA9FqVM3hO637sJc5m6hsgSpr3hjubtwDmTZeogrdp3vqzjtc1jaLY5wC94FJUiHORk1ogarasQaoL7nnLudiv3XvVOp+ts7c2OzG/BmepQlh+/gGGrGvmV2CKm56B3TikyxkOvfg7vxQvBuuecg5WGT5OGNGXovwifrLfGOM7/O5mdK6juszE/IJG1WacTfr6MishoZZdm0NKxiyyMeEFNDW9IJRznDX/P8gYvOiDmSox0qBLwHBhVdmU51QYorHKYkOUmVwEep1ukvwx1tI2lbzLDixb6Ur8YniLcrcm7emVjIN2jBWXOFpx97+hr4vwruOLmIxIH7NbOUew=
  - secure: Ok94pyN1fyXn0ibH/iEWF5PKmDRKKeYXxo7BAaB92aKXkFGFtTqacCdVN/Q5G+ZSzf/uOWTbp5cPfHiWsPhJBmIMG3QRxS6YX550n2maYaIaSxD2xa680HzMNoAepZ0e5+XYyFTzayEFN7E7gUMtXQM8P/tcRQa+yH9XjTAOOlqXt5DgZNaUMCp+bDMU8ArZ/Wi3KrqTuSOG6a6v0iSRm0wwczzEttSVO8ykcGOsS+46J+27kj2eUnBJ2D6gRvtv9PPzGSXZrS37l4ZsgYZ5n3sK2wC95Tc/29nXysrPU4CpDKIKc6+k3CpzSIdASwtj1aHX0GjgPOHVayIuay01t2ihsTLZlM4rGsjz+yx7tWSnlfmBttOt3vohsV5jRJIgzk/joYyRLpjQomie6ID3Ft+AvvQ06fa3fpcvZdzkILs4ruFpZtbEv72EdUGzbN1RtR5367kpaPHVgOOPNTCgubgWdDkjewxFrDQ3/rEaHOmf0uCXNmFbV9gz/dzKTlvYDVaCRaObqp24dv8QufLPFgc9fKlqtHMIJDhhimPLI8kDWXFvk9lJdrNUcBZiogpc1XpBb0kDzv+WMkYvW2mAxcN77L2YQ95Rk0O2aFillsCwjowjKNqdg3zDYyY+IjlduqSQm1gbeuKrNIzDQSuifN+a/2NjZI88SIMfIHCQysw=
  - SONA_USER=snowplow
  - BINTRAY_USER=deploy-snowplow-maven
